test: vitest 커버리지 리포트 html 작성 셋업
GoodOnuii/next pull request #2
Opened 2023-01-31 07:32 UTC by vivi-onuii

- vitest 및 vitest/ui 를 각각 0.28 이상으로 버전업; `test.coverage.reporter` 는 v0.26 이상부터 사용할 수 있음 
- `__tests__/unit/coverage` 로 reportsDirectory 설정

2023-01-31 07:49 UTC, doby-onuii approved these changes

2023-01-31 08:33 UTC, doby-onuii commented
html 파일 잘 생성되는 거 확인 되었습니다~!!

2023-02-01 12:57 UTC, momenthana requested changes

2023-02-01 12:57 UTC, momenthana commented on vitest.config.ts
> +      reportsDirectory: './__tests__/unit/coverage',
```
# testing
/coverage
```
로 `.gitignore` 파일의 값에 따라 directory를 잡고 coverage 파일이 git changed files로 잡히지 않도록 변경되어야 할 것 같습니다.
(빌드 후 깃에 올라오지 않고 버려야 함)

2023-02-02 10:27 UTC, vivi-onuii commented on vitest.config.ts
> +      reportsDirectory: './__tests__/unit/coverage',
`/__tests__/unit/*` 으로 작성했슴다.

2023-02-02 10:50 UTC, doby-onuii approved these changes

2023-02-06 02:55 UTC, momenthana approved these changes

2023-02-06 02:57 UTC, merged